development:
  adapter: postgresql
  encoding: unicode
  database: timekeeper_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: timekeeper_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: timekeeper_production
  pool: 5
